<h1>Retreat registrations</h1>

<?php
if (count($this->items)>0) {
    $keys = array_keys($this->items[0]);
    echo "<table>";
    echo "<tr>";
    foreach ($keys as $key) {
        echo "<th>$key</th>";
    }
    echo "</tr>";
    foreach ($this->items as $item) {
    echo "<tr>";
        foreach ($item as $i) {
            echo "<td>$i</td>";
        }
    echo "</tr>";
    }
    echo "</table>";
} else {
    echo "<p>No records</p>";
}

