<script type="text/javascript">
    $(function() {
        $("#datefrom").datepicker({dateFormat: 'yy-mm-dd' , minDate: new Date(2010, 7 - 1, 9) , maxDate: new Date(2010, 7 - 1, 16)});
        $("#dateto").datepicker({dateFormat: 'yy-mm-dd' , minDate: new Date(2010, 7 - 1, 9) , maxDate: new Date(2010, 7 - 1, 16)});
    });
</script>
<h1>Retreat with Chögyal Namkhai Norbu</h1>

<p>on the Dzogchen Teaching

„The Base, Path and Fruit of Ati Dzogchen”, Terma of Rigdzin Changchub Dorje,

will be held in the period of  July 9-16, 2010
</p


<p>Participation fees for:</p>

<ul>
    <li>Non-members - 220 euro</li>
    <li>Ordinary members - 175 euro</li>
    <li>Sustaining members (Merigar) - 45 euro</li>
    <li>Sustaining members (non Merigar) - 130 euro</li>
    <li>Reduced members - 110 euro</li>
</ul>

<p>In the Gar there will be a lunch served consisting of fresh and healthy food, prepared by retreat participants.</p>

<p>The separate children area will be created. It will be possible to listen to the Teaching through webcast there.</p>

<p>After the participation fees add pls:</p>
 

<p>Per one day – 30 euro with usual discounts for members.</p>

<p>For pensioners and students – 110 euro; the conformational document should be shown on the spot. Kids up till 18 years old - for free.</p>

<p>Please fill up the registration form:</p>


<?php echo $this->form; ?>

<p>If you have any problem or question please contact <a href="mailto:martin.kourim@gmail.com">Martin</a>.</p>
