<h1>Retreat with Chögyal Namkhai Norbu</h1>

<p>on the Dzogchen Teaching

„The Base, Path and Fruit of Ati Dzogchen”, Terma of Rigdzin Changchub Dorje,

will be held in the period of  July 9-16, 2010
</p


<p>Participation fees for:</p>

<ul>
    <li>Non-members - 220 euro</li>
    <li>Ordinary members - 175 euro</li>
    <li>Sustaining members (Merigar) - 45 euro</li>
    <li>Sustaining members (non Merigar) - 130 euro</li>
    <li>Reduced members - 110 euro</li>
</ul>

<p>There will be served lunch in the Gar with healthy and fresh food, prepared by retreat participants. The separate children area will be created, were will be possible to listen the Teaching through webcast.</p>

<p>Please fill up the registration form:</p>

<?php echo $this->form; ?>

