<script type="text/javascript">
    $(function() {
        $("#datefrom").datepicker({dateFormat: 'yy-mm-dd' , minDate: new Date(2010, 7 - 1, 9) , maxDate: new Date(2010, 7 - 1, 16)});
        $("#dateto").datepicker({dateFormat: 'yy-mm-dd' , minDate: new Date(2010, 7 - 1, 9) , maxDate: new Date(2010, 7 - 1, 16)});
    });
</script>
<h1>Retragerea de Invataturi Dzogchen cu Chögyal Namkhai Norbu</h1>

<p>Va aducem la cunostinta pe aceasta cale costurile de participare la

    Retragerea de Invataturi Dzogchen cu Chögyal Namkhai Norbu

    avand tema "Baza, Calea si Fructul in Ati Dzogchen" - o invatatura de
    tip terma al lui Rigzin Changchub Dorje care va avea loc in perioada
    9-16 iulie 2010, dupa cum urmeaza:

</p

<ul>
    <li>Non-membri: 220 Euro</li>
    <li>Membri obisnuiti: 175 Euro</li>
    <li>Membri sustinatori (afiliati la centrul Merigar): 45 Euro</li>
    <li>Membri sustinatori (afiliati la un alt Gar): 135 Euro</li>
    <li>Membri cu reducere: 110 Euro</li>
</ul>

<p>Pe durata retragerii cursantii vor putea servi o masa la fata locului
    preparata din ingrediente proaspete si sanatoase.</p>

<p>Copiilor mici li se va asigura un loc de joaca unde supraveghetorii
    acestora vor putea urmari retragerea prin webcast.
</p>

<p>Cei care nu pot fi prezenti pe intreaga durata a retragerii vor putea
    sa-si cumpere bilete de zi in valoare de 30 Euro (cu reducerile de
    rigoare pentru membri). Pensionarii si studentii vor plati 110 Euro,
    minorii au acces gratuit.
</p>


 

<?php echo $this->form; ?>

<p>Va invitam asadar sa va completati formularele de inregistrare.
    Pentru intrebari suplimentare va rugam sa ne contactati la adresa:
    <a href="mailto:martin.kourim@gmail.com">Martin</a>.</p>
