<?php

/**
 * Registration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Registration extends BaseRegistration
{

    public static function save($array)
    {
        $r  = new Registration();
        $r->name = $array['name'];
        $r->surname = $array['surname'];
        $r->email = $array['email'];


        $r->save();
    }

}