Users:
  columns:
    idUser:
      primary: true
      type: integer(4)
      autoincrement: true
    email:
      unique: true
      type: string(255)
      notnull: true
    password:
      type: string(255)
    groupMember:
      type: integer(4)
Groups:
  columns:
    idGroup:
      primary: true
      type: integer(4)
      autoincrement: true
    name:
      type: string(255)
      notnull: true
Registration:
  columns:
    id:
      primary: true
      type: integer(4)
      autoincrement: true
    name: string(255)
    surname: string(255)
    email: string(255)
    country: string(255)
    gar: integer(4)
    membershipnumber : string(20)
    membershiptype: integer(4)
    recording: boolean
    wholeretreat: boolean
    datefrom: string(30)
    dateto: string(30)
    children: boolean
    childrencount: integer(4)
    other: boolean
    eat: boolean
    rem: string
actAs:
  Timestampable:
    created:
      name: created
    updated:
      name: updated
options:
  type: INNODB
  collate: utf8_general_ci
  charset: utf8
      
